// The Amanorsac collection as the Hub knows it when it cannot reach the
// website. GET https://amanorsac.studio/api/catalog is the live copy,
// built by worker.js from catalog.json, and it wins whenever it answers
// - so a new app, a new price or a new build reaches the Hub without a
// Hub release. This file is the last resort behind that, and the only
// thing it really has to get right is the names, the icons and which
// app is which: everything else is refreshed the moment the site is
// reachable again.
//
// The icons here are bundled files, so they draw with no network at
// all. The screenshots are addresses on the site, which is honest about
// what they are: offline they will not load, and the Hub falls back to
// the icon, then to the app's initials.
//
// GENERATED - do not edit. Run:  node tools/hub-catalog.mjs
// Editing this by hand is how it ends up describing a version that no
// longer exists, which is the one thing a fallback must not do.
window.HUB_CATALOG = {
  generatedAt: '2026-09-16',
  apps: [
    {"id":"performlive","name":"PerformLive","tagline":"Live performance, perfected.","blurb":"Stem decks, scenes and warm pads laid out for a service. Free for thirty days.","kind":"app","status":"available","soon_note":null,"free":true,"licensed":true,"color":"#7B7DF7","icon":"assets/performlive.webp","art":"https://amanorsac.studio/images/apps/performlive.webp","page":"https://amanorsac.studio/performlive.html","platforms":{"windows":{"size":"5.6 MB","version":"0.4.1"},"mac-arm64":{"size":"9.14 MB","version":"0.4.1"},"mac-x64":{"size":"9.16 MB","version":"0.4.1"}}},
    {"id":"chordlight88","name":"Chordlight 88","tagline":"What your hands just played, in the language you think in.","blurb":"Eighty-eight keys that name what you played, in notes, numbers or solfa.","kind":"app","status":"available","soon_note":null,"free":false,"licensed":false,"color":"#9A7CFF","icon":"assets/icons/chordlight88.svg","art":"https://amanorsac.studio/images/apps/chordlight88/notes.webp","page":"https://amanorsac.studio/chordlight88.html","platforms":{"windows":{"size":"156 MB","version":"1.0.0"},"mac":{"size":"339 MB","version":"1.0.0"}}},
    {"id":"secondout","name":"SecondOut","tagline":"One master bus. Two independent outputs.","blurb":"Send your master to a second output device, drift-corrected, without touching the mix.","kind":"plugin","status":"available","soon_note":null,"free":false,"licensed":true,"color":"#3fe083","icon":"assets/secondout-icon.png","art":"https://amanorsac.studio/images/apps/secondout-screenshot.png","page":"https://amanorsac.studio/secondout.html","platforms":{"windows":{"size":"5 MB","version":"1.3.2"},"mac":{"size":"12 MB","version":"1.3.2"}}},
    {"id":"stemsorter","name":"Something big coming","tagline":"More when it is ready.","blurb":"Point it at a folder of stems and it files them the way you would have.","kind":"app","status":"hidden","soon_note":null,"free":false,"licensed":true,"color":"#2ad2e8","icon":"assets/icons/stemsorter.svg","art":"https://amanorsac.studio/images/apps/stemsorter/02-analyzed.webp","page":"https://amanorsac.studio/apps.html","platforms":{"windows":{"size":"9 MB","version":"0.6.0"},"mac":{"size":"12 MB","version":"0.6.0"}}},
    {"id":"ambanalog","name":"AMB Analog","tagline":"Ten analog machines, built from the ground up.","blurb":"Tape, tubes and transformers on one strip, for glue that sounds played rather than processed.","kind":"plugin","status":"available","soon_note":null,"free":false,"licensed":true,"color":"#D4A24C","icon":"assets/icons/ambanalog.svg","art":"https://amanorsac.studio/images/apps/analog/A01.webp","page":"https://amanorsac.studio/ambanalog.html","platforms":{"windows":{"size":"297 MB","version":"1.0.0"},"mac":{"size":"745 MB","version":"1.0.0"}}},
    {"id":"alignpro","name":"Align Pro","tagline":"Align every mic. Hear exactly how much.","blurb":"Phase and time alignment across every microphone on the kit, found automatically.","kind":"plugin","status":"available","soon_note":null,"free":false,"licensed":true,"color":"#2E9BF0","icon":"assets/icons/alignpro.svg","art":"https://amanorsac.studio/images/apps/alignpro/auto.png","page":"https://amanorsac.studio/alignpro.html","platforms":{"windows":{"size":"7 MB","version":"1.0.0"},"mac":{"size":"14 MB","version":"1.0.0"}}},
    {"id":"afdgate","name":"AFD Gate","tagline":"Filter the trigger. Shape the tail.","blurb":"A gate that listens to the drum rather than the level, so it never clips a tail.","kind":"plugin","status":"available","soon_note":null,"free":false,"licensed":false,"color":"#4A8BF0","icon":"assets/icons/afdgate.svg","art":"https://amanorsac.studio/images/apps/afdgate/ui.webp","page":"https://amanorsac.studio/afdgate.html","platforms":{"windows":{"size":"11 MB","version":"1.3.0"},"mac":{"size":"33 MB","version":"1.3.0"}}},
    {"id":"aether","name":"AETHER","tagline":"Air you can aim. A dynamic air exciter for vocals, choir and the mix bus.","blurb":"Air you can aim: a dynamic exciter for vocals, choir and the mix bus.","kind":"plugin","status":"available","soon_note":null,"free":false,"licensed":true,"color":"#35E0F0","icon":"assets/icons/aether.svg","art":"https://amanorsac.studio/images/apps/aether/ui.webp","page":"https://amanorsac.studio/aether.html","platforms":{"windows":{"size":"4 MB","version":"1.0.0"},"mac":{"size":"10 MB","version":"1.0.0"}}},
    {"id":"pulseroom","name":"PulseRoom","tagline":"Every mixing answer. One tempo.","blurb":"Your reference desk: delay and reverb times, EQ cheat sheet, compression, mix chains.","kind":"app","status":"available","soon_note":null,"free":true,"licensed":false,"color":"#3fd3e4","icon":"assets/pulseroom-logo.svg","art":"https://amanorsac.studio/images/apps/S6-eq-cheat-sheet.webp","page":"https://amanorsac.studio/pulseroom.html","platforms":{"windows":{"size":"78 MB","version":"1.0"},"mac":{"size":"171 MB","version":"1.0"}}},
    {"id":"nebulatide2","name":"Nebula Tide 2","tagline":"The pad rises as it fades. Shimmer, your own presets, and a drag to the timeline.","blurb":"The second tide: new beds, a wider stage, and a price you set yourself.","kind":"app","status":"available","soon_note":null,"free":false,"licensed":true,"color":"#4FE3FF","icon":"assets/nt-logo.webp","art":"https://amanorsac.studio/images/apps/nt2/stage.webp","page":"https://amanorsac.studio/nebulatide2.html","platforms":{"windows":{"size":"278 MB","version":"2.1"},"mac":{"size":"312 MB","version":"2.1"},"android":{"size":"263 MB","version":"2.1"}}},
    {"id":"nebulatide","name":"Nebula Tide","tagline":"An ocean of sound. In every key.","blurb":"Endless, seamless drone pads recorded in all twelve keys. Deep Current included.","kind":"app","status":"available","soon_note":null,"free":true,"licensed":false,"color":"#4FE3FF","icon":"assets/nt-logo.webp","art":"https://amanorsac.studio/images/apps/nt-idle.webp","page":"https://amanorsac.studio/nebulatide.html","platforms":{"windows":{"size":"279 MB","version":"1.2.2"},"mac":{"size":"289 MB","version":"1.2.2"}}},
    {"id":"harmoniemd","name":"HarmonieMD","tagline":"The rehearsal studio for choirs.","blurb":"The choir rehearsal studio: parts, setlists and a multi-track editor.","kind":"app","status":"coming_soon","soon_note":null,"free":false,"licensed":true,"color":"#3ED598","icon":"assets/harmoniemd.png","art":"https://amanorsac.studio/images/HD-04-md-editor.webp","page":"https://amanorsac.studio/apps.html","platforms":{}},
  ],
};
